// Mock data for demonstration purposes
// In production, this would be replaced with CMS API calls
// Compatible with: ButterCMS, Prismic, Sanity, Contentful

import type { Product, Category } from '@/types'

export const categories: Category[] = [
  {
    id: '1',
    slug: 'engine-parts',
    name: 'Engine Parts',
    description: 'High-performance engine components',
    image: 'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=400',
  },
  {
    id: '2',
    slug: 'brakes',
    name: 'Brakes',
    description: 'Premium brake systems and components',
    image: 'https://images.unsplash.com/photo-1625047509168-a7026f36de04?w=400',
  },
  {
    id: '3',
    slug: 'suspension',
    name: 'Suspension',
    description: 'Advanced suspension systems',
    image: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=400',
  },
  {
    id: '4',
    slug: 'exhaust',
    name: 'Exhaust Systems',
    description: 'Performance exhaust components',
    image: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=400',
  },
  {
    id: '5',
    slug: 'electrical',
    name: 'Electrical',
    description: 'Electrical systems and components',
    image: 'https://images.unsplash.com/photo-1621939514649-280e2ee25f60?w=400',
  },
  {
    id: '6',
    slug: 'accessories',
    name: 'Accessories',
    description: 'Premium automotive accessories',
    image: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=400',
  },
]

export const products: Product[] = [
  {
    id: '1',
    slug: 'performance-air-filter',
    name: 'High-Flow Performance Air Filter',
    description: 'Premium high-flow air filter designed to increase horsepower and acceleration. Features washable and reusable cotton gauze filter media for excellent filtration and airflow. Compatible with most standard air filter housings.',
    shortDescription: 'Increase horsepower with our premium high-flow air filter',
    price: 59.99,
    salePrice: 49.99,
    currency: 'USD',
    images: [
      {
        id: '1-1',
        url: 'https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?w=800',
        alt: 'Performance Air Filter',
        isPrimary: true,
      },
    ],
    category: categories[0],
    brand: 'K&N',
    sku: 'KN-33-2304',
    inStock: true,
    stockQuantity: 45,
    tags: ['performance', 'air filter', 'engine'],
    specifications: [
      { name: 'Height', value: '1.5', unit: 'inches' },
      { name: 'Outside Diameter', value: '9', unit: 'inches' },
      { name: 'Inside Diameter', value: '6', unit: 'inches' },
      { name: 'Filtration Efficiency', value: '98.5', unit: '%' },
    ],
    rating: 4.8,
    reviewCount: 234,
    featured: true,
    isNew: false,
    isBestSeller: true,
    createdAt: '2024-01-15T00:00:00Z',
    updatedAt: '2024-11-01T00:00:00Z',
  },
  {
    id: '2',
    slug: 'ceramic-brake-pads',
    name: 'Ceramic Brake Pads Set',
    description: 'Premium ceramic brake pads offering superior stopping power with minimal dust and noise. Engineered for extended wear and consistent performance in all weather conditions. Includes hardware kit for easy installation.',
    shortDescription: 'Superior stopping power with minimal dust',
    price: 89.99,
    currency: 'USD',
    images: [
      {
        id: '2-1',
        url: 'https://images.unsplash.com/photo-1625047509168-a7026f36de04?w=800',
        alt: 'Ceramic Brake Pads',
        isPrimary: true,
      },
    ],
    category: categories[1],
    brand: 'Brembo',
    sku: 'BRM-P06084',
    inStock: true,
    stockQuantity: 28,
    tags: ['brakes', 'ceramic', 'safety'],
    specifications: [
      { name: 'Material', value: 'Ceramic composite' },
      { name: 'Operating Temperature', value: '-40 to 750', unit: '°F' },
      { name: 'Friction Coefficient', value: '0.45' },
    ],
    rating: 4.9,
    reviewCount: 189,
    featured: true,
    isNew: false,
    isBestSeller: true,
    createdAt: '2024-02-01T00:00:00Z',
    updatedAt: '2024-11-05T00:00:00Z',
  },
  {
    id: '3',
    slug: 'coilover-suspension-kit',
    name: 'Adjustable Coilover Suspension Kit',
    description: 'Complete coilover suspension kit featuring fully adjustable damping and ride height. Precision-engineered for improved handling, cornering, and overall vehicle dynamics. Includes all necessary mounting hardware.',
    shortDescription: 'Fully adjustable suspension for ultimate control',
    price: 1299.99,
    salePrice: 1149.99,
    currency: 'USD',
    images: [
      {
        id: '3-1',
        url: 'https://images.unsplash.com/photo-1580273916550-e323be2ae537?w=800',
        alt: 'Coilover Suspension Kit',
        isPrimary: true,
      },
    ],
    category: categories[2],
    brand: 'BC Racing',
    sku: 'BC-BR-RA',
    inStock: true,
    stockQuantity: 12,
    tags: ['suspension', 'coilovers', 'performance'],
    specifications: [
      { name: 'Adjustment Range', value: '30', unit: 'clicks' },
      { name: 'Spring Rate Front', value: '8', unit: 'kg/mm' },
      { name: 'Spring Rate Rear', value: '6', unit: 'kg/mm' },
      { name: 'Height Adjustment', value: '3', unit: 'inches' },
    ],
    rating: 4.7,
    reviewCount: 156,
    featured: true,
    isNew: true,
    isBestSeller: false,
    createdAt: '2024-10-01T00:00:00Z',
    updatedAt: '2024-11-10T00:00:00Z',
  },
  {
    id: '4',
    slug: 'performance-exhaust-system',
    name: 'Cat-Back Performance Exhaust System',
    description: 'Complete cat-back exhaust system crafted from premium stainless steel. Delivers significant horsepower gains, enhanced exhaust note, and improved fuel efficiency. Features mandrel-bent tubing and polished tips.',
    shortDescription: 'Unleash power with our cat-back exhaust system',
    price: 899.99,
    currency: 'USD',
    images: [
      {
        id: '4-1',
        url: 'https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?w=800',
        alt: 'Performance Exhaust System',
        isPrimary: true,
      },
    ],
    category: categories[3],
    brand: 'MagnaFlow',
    sku: 'MAG-15845',
    inStock: true,
    stockQuantity: 8,
    tags: ['exhaust', 'performance', 'stainless steel'],
    specifications: [
      { name: 'Material', value: 'T304 Stainless Steel' },
      { name: 'Pipe Diameter', value: '3', unit: 'inches' },
      { name: 'Tip Diameter', value: '4', unit: 'inches' },
      { name: 'Power Gain', value: '15-20', unit: 'HP' },
    ],
    rating: 4.6,
    reviewCount: 98,
    featured: false,
    isNew: false,
    isBestSeller: false,
    createdAt: '2024-03-15T00:00:00Z',
    updatedAt: '2024-10-20T00:00:00Z',
  },
  {
    id: '5',
    slug: 'led-headlight-kit',
    name: 'LED Headlight Conversion Kit',
    description: 'Ultra-bright LED headlight bulbs offering 300% more light than stock halogen bulbs. Features advanced cooling system, plug-and-play installation, and 50,000-hour lifespan. DOT compliant.',
    shortDescription: '300% brighter than stock with easy installation',
    price: 129.99,
    salePrice: 99.99,
    currency: 'USD',
    images: [
      {
        id: '5-1',
        url: 'https://images.unsplash.com/photo-1621939514649-280e2ee25f60?w=800',
        alt: 'LED Headlight Kit',
        isPrimary: true,
      },
    ],
    category: categories[4],
    brand: 'Philips',
    sku: 'PHL-12794',
    inStock: true,
    stockQuantity: 62,
    tags: ['lighting', 'LED', 'electrical'],
    specifications: [
      { name: 'Lumens', value: '12000', unit: 'lm' },
      { name: 'Color Temperature', value: '6000', unit: 'K' },
      { name: 'Wattage', value: '35', unit: 'W' },
      { name: 'Lifespan', value: '50000', unit: 'hours' },
    ],
    rating: 4.8,
    reviewCount: 312,
    featured: true,
    isNew: false,
    isBestSeller: true,
    createdAt: '2024-01-20T00:00:00Z',
    updatedAt: '2024-11-08T00:00:00Z',
  },
  {
    id: '6',
    slug: 'carbon-fiber-spoiler',
    name: 'Carbon Fiber Rear Spoiler',
    description: 'Premium carbon fiber rear spoiler providing enhanced aerodynamics and aggressive styling. Hand-laid carbon fiber construction with UV-protective clear coat. Includes all mounting hardware and installation instructions.',
    shortDescription: 'Enhance aerodynamics with premium carbon fiber',
    price: 549.99,
    currency: 'USD',
    images: [
      {
        id: '6-1',
        url: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800',
        alt: 'Carbon Fiber Spoiler',
        isPrimary: true,
      },
    ],
    category: categories[5],
    brand: 'Seibon',
    sku: 'SEI-TL1011',
    inStock: true,
    stockQuantity: 5,
    tags: ['carbon fiber', 'aerodynamics', 'accessories'],
    specifications: [
      { name: 'Material', value: 'Carbon Fiber 2x2 Twill' },
      { name: 'Finish', value: 'Clear Coat Gloss' },
      { name: 'Weight', value: '4.5', unit: 'lbs' },
    ],
    rating: 4.7,
    reviewCount: 67,
    featured: false,
    isNew: true,
    isBestSeller: false,
    createdAt: '2024-09-10T00:00:00Z',
    updatedAt: '2024-11-12T00:00:00Z',
  },
  {
    id: '7',
    slug: 'oil-catch-can',
    name: 'Baffled Oil Catch Can Kit',
    description: 'High-quality baffled oil catch can designed to prevent oil vapor from entering your intake system. Features internal baffle system, drain valve, and dipstick. Complete with all mounting brackets and hoses.',
    shortDescription: 'Protect your engine with our baffled catch can',
    price: 159.99,
    currency: 'USD',
    images: [
      {
        id: '7-1',
        url: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=800',
        alt: 'Oil Catch Can',
        isPrimary: true,
      },
    ],
    category: categories[0],
    brand: 'Mishimoto',
    sku: 'MSH-MMBCC',
    inStock: true,
    stockQuantity: 34,
    tags: ['engine', 'oil', 'maintenance'],
    specifications: [
      { name: 'Capacity', value: '10', unit: 'oz' },
      { name: 'Material', value: 'Billet Aluminum' },
      { name: 'Mounting', value: 'Universal' },
    ],
    rating: 4.9,
    reviewCount: 145,
    featured: false,
    isNew: false,
    isBestSeller: false,
    createdAt: '2024-04-05T00:00:00Z',
    updatedAt: '2024-10-15T00:00:00Z',
  },
  {
    id: '8',
    slug: 'racing-seat',
    name: 'FIA Approved Racing Seat',
    description: 'Professional-grade racing seat with FIA homologation. Features carbon fiber shell, fire-retardant fabric, and aggressive bolstering for maximum support. Includes side mounts and hardware.',
    shortDescription: 'Professional racing seat with FIA approval',
    price: 1499.99,
    salePrice: 1299.99,
    currency: 'USD',
    images: [
      {
        id: '8-1',
        url: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=800',
        alt: 'Racing Seat',
        isPrimary: true,
      },
    ],
    category: categories[5],
    brand: 'Recaro',
    sku: 'REC-POLE',
    inStock: true,
    stockQuantity: 3,
    tags: ['racing', 'seat', 'interior'],
    specifications: [
      { name: 'Shell Material', value: 'Carbon Fiber' },
      { name: 'Weight', value: '19', unit: 'lbs' },
      { name: 'FIA Standard', value: '8855-1999' },
      { name: 'Mounting', value: 'Side Mount' },
    ],
    rating: 5.0,
    reviewCount: 42,
    featured: true,
    isNew: true,
    isBestSeller: false,
    createdAt: '2024-10-15T00:00:00Z',
    updatedAt: '2024-11-14T00:00:00Z',
  },
]

export const featuredProducts = products.filter((p) => p.featured)
export const newProducts = products.filter((p) => p.isNew)
export const bestSellers = products.filter((p) => p.isBestSeller)
